### ISSUE TITLE
Variable type ' CustomLookAndFeel' is an abstract class error

### ISSUE THREAD

**Issue by jazzman31** [HiFi-LoFi/KlangFalter#5]
Hi,
I’m getting this error and I would love to get work this baby!

Kind regards,

Thanks

Jean

**Comment by HiFi-LoFi** [comment]
Hi,

sorry for not answering earlier, I was more in making music than in making music software the recent time... ;-)

I've just updated the KlangFalter code to Juce 4.2.3, so these compiling issues should be solved now.

Regards, Uli

**Comment by skoleyuno** [comment]
Hey Uli,

Do you think it would be possible to update the plugin to Juce 5.4.3? I had a try, and was able to clear any build issues, however, got a linker error:

Undefined symbols for architecture x86_64:
  "juce::Atomic<int>::compareAndSetValue(int, int)"

Cheers
