### ISSUE TITLE
[Feature Request] Include some impulse response

### ISSUE THREAD

**Issue by daeavelwyn** [HiFi-LoFi/KlangFalter#6]
Hi,

Should it be possible to include ready to use impulse response with KlangFalter ? 

Regards,

**Comment by HiFi-LoFi** [comment]
Hi daeavelwyn,

basically I'd love to include some good impulse responses, but that would mean that I had to make sure that everything is alright with the IR's licenses and copyright, which - to be honest - I'm currently not willing to deal with at the moment... It's just a hobby and I don't earn a single cent with it, I hope you understand this.

Regards, Uli
