### ISSUE TITLE
Reading FLAC audio files

### ISSUE THREAD

**Issue by unfa** [HiFi-LoFi/KlangFalter#9]
It seems that Klangfalter is unable to read FLAC files.
The IR plugin by Tom Shilagyli reads FLACs just fine :)

I personally store all my samples (including IR files) in FLAC. I guess I'm not the only one who'd like so see this feature :)

https://github.com/KXStudio/Repository/issues/56

**Comment by HiFi-LoFi** [comment]
Hi unfa,

thanks for reporting.

KlangFalter just supports what is supported by the underlying JUCE framework and what is registered by AudioFormatManager::registerBasicFormats(). Having a look at this function, JUCE_USE_FLAC must be defined. I guess you're on Linux? Unfortunately, I'm currently using only Mac at home, so no Linux support at the moment from my side... ;-) 

However, I've that the originating issue has been resolved already, so I'll close this one as well:
https://github.com/KXStudio/Repository/issues/56

Regards, Uli
